name: Build and Push Caddy Docker Image

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间的午夜触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '20'  # 设置 Node.js 版本为 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            linkmew/caddy-alidns:latest
            linkmew/caddy-alidns:${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
